import type { OpsCase } from "./types";

/**
 * The 19 open cases with the reassessed plan already applied: priority against
 * the policy clause rather than the inherited queue, the correct licensed
 * trade, owner, access plan, dependencies, cost, communication and fallback.
 *
 * Nine of these were wrongly prioritised or wrongly assigned when inherited.
 * The `rationale` field says why each one changed — keep it, it is what an
 * operator reads before overriding the engine.
 */
export const SEED_CASES: OpsCase[] = [
  {
    id: "M-101",
    workstream: "In-Home Services",
    homeId: "H-1001",
    zone: "Pinecrest",
    priority: "P1 - repeat-repair review",
    risk: "AMBER",
    owner: "Jordan Lee",
    status: "New",
    action: "Release hold 08:30 / vendor on site 09:15 / moisture reading by 10:20",
    assignment: "FlowRight Plumbing (licensed, 92% first-visit resolution, best repeat-repair diagnostics) 09:15-11:15. RELEASE BY 08:30. Marcus Bell takes a moisture reading 09:55-10:20.",
    accessPlan: "Resident home until 11:30, and again after 17:00. No vendor lockbox - Resident must grant entry. All work must complete before 11:30.",
    dependencies: "Release by 08:30 or the hold lapses. If the moisture reading is material, escalate to DryNow Restoration (IICRC-certified, $650 minimum) under Alex Moreno's $1,500 containment authority. Do not pre-book DryNow before the reading.",
    cost: "$450 estimate (Home limit $500). DryNow $650+ only if moisture is material.",
    communication: "SMS by 08:15: keep the valve closed, do not use the sink, technician confirmed with ETA. P1 requires updates every 60 minutes while the plan is uncertain. Explain explicitly that this is a root-cause review by a licensed plumber, not another tighten - the Resident has had this fail twice.",
    fallback: "No second plumber covers Pinecrest (Rapid Rooter excludes PC and KN). Fallback is FlowRight in the Resident's post-17:00 window the same day, or Tuesday 08:00-11:00. Flag as single-source vendor risk.",
    rationale: "Water is contained (Resident closed the valve), so this is not P0 'active uncontrolled water'. But it is a REPEAT REPAIR within 60 days (prior fix 14 Sep), which triggers the root-cause policy. The prior fix was done by an unlicensed generalist, tightened a connection, replaced no part, and took no moisture reading. Requires a licensed trade and a root-cause diagnosis, not another adjustment.",
    updates: []
  },
  {
    id: "M-102",
    workstream: "In-Home Services",
    homeId: "H-1002",
    zone: "Doral",
    priority: "P1 - containment at P0 urgency",
    risk: "AMBER",
    owner: "Maya Chen",
    status: "New",
    action: "Containment on site by 10:15 / qualified diagnostic 13:30",
    assignment: "CANCEL Budget Breeze tentative 08:00-10:00 (no technician confirmed). Book Apex Climate 13:30-16:30 - BOOK BY 09:00. Elena Ruiz delivers and sets up the portable AC unit 09:15-10:15.",
    accessPlan: "Resident home all day Monday. Vendor parks in the guest area. No access constraint.",
    dependencies: "Book Apex by 09:00 or the emergency slot is lost. Portable AC available from 08:30 at Doral storage; H-1002 is confirmed suitable (vents through a sliding window). DO NOT approve the $5,900 replacement without a measured onsite diagnosis.",
    cost: "$139 diagnostic. Portable AC $0 (inventory). Replacement decision only after diagnosis; $5,900 exceeds the $750 Home limit and requires Homeowner approval.",
    communication: "Call by 08:15 with the plan and the portable-AC ETA. Update every 60 minutes. State explicitly that no $5,900 replacement is approved without a measured diagnosis, and that a cooled room is being provided today either way.",
    fallback: "The portable AC sustains containment into Tuesday; Apex has Tuesday 08:00-11:00. Budget Breeze is NOT a fallback - recommend a formal probation review based on this incident.",
    rationale: "'No AC with high indoor temperature' is the literal P1 example in policy. Two young children in the Home with 83F and rising elevates containment urgency. The real issue is not priority: it is a $5,900 replacement estimate sent by text with no onsite diagnosis, from a vendor on probation (61% on-time, 58% first-visit resolution, 24% callback rate, two missed appointments).",
    updates: []
  },
  {
    id: "M-103",
    workstream: "In-Home Services",
    homeId: "H-1003",
    zone: "Coconut Grove",
    priority: "P0",
    risk: "RED",
    owner: "Maya Chen",
    status: "New",
    action: "Release 08:30 / on site 09:30 / findings reported by 11:30",
    assignment: "CANCEL HandyHub generalist visit 11:00-12:00. BrightLine Electric (licensed electrical contractor, provides test results and panel photos) 09:30-11:30. RELEASE BY 08:30.",
    accessPlan: "Lockbox authorised 09:00-13:00; code current in the app. Resident departs at 09:00. BrightLine's window sits entirely inside the lockbox window.",
    dependencies: "Release by 08:30. Confirm with the Resident that the breaker remains OFF. The lockbox window closes at 13:00, which rules out BrightLine's alternative 14:00-16:00 slot unless the Resident returns.",
    cost: "$145 diagnostic plus repair (estimate $175). Home limit $1,000.",
    communication: "Acknowledge within 10 minutes (P0). Confirm the breaker stays off and nothing is re-energised. Confirm the lockbox code. Report findings and next steps at close of visit.",
    fallback: "BrightLine's alternative 14:00-16:00 slot requires the Resident to be present (lockbox expires 13:00). CRITICAL: BrightLine is the ONLY electrical vendor in the network, with 2 jobs/day and no backup. Escalate as single-source risk.",
    rationale: "'Electrical burning' is the literal P0 example in policy - the outlet sparked and produced a burning odour. It was entered as P2 AND assigned to HandyHub, which the vendor sheet explicitly marks as not licensed for electrical work. Two policy violations in one case: wrong priority and wrong trade.",
    updates: []
  },
  {
    id: "M-104",
    workstream: "In-Home Services",
    homeId: "H-1004",
    zone: "Kendall",
    priority: "P0",
    risk: "RED",
    owner: "Alex Moreno",
    status: "New",
    action: "RELEASE 08:15 - first and hardest deadline of the day / on site 08:45 / Home secured before 10:15",
    assignment: "KeyGuard Locksmith (97% on-time, 91% first-visit resolution, 4.9/5) 08:45-10:15. RELEASE BY 08:15.",
    accessPlan: "Resident home only until 10:15. No lockbox. All work must complete while the Resident is present.",
    dependencies: "Release by 08:15. This release ALSO enables the R-201 Brickell rekey at 14:00-16:00 - KeyGuard can route Kendall to Brickell only if the first job is released by 08:15. One call protects two cases.",
    cost: "$95 trip fee plus hardware (estimate $250). Home limit $400. Covered by emergency containment authority - no prior Homeowner approval required.",
    communication: "Acknowledge within 10 minutes (P0). Confirm the 08:45 arrival and that the Home will be secured before the 10:15 departure. If the timeline is at risk, tell the Resident before 09:30, not at 10:10.",
    fallback: "If not complete by 10:15: install a temporary secure lock or hasp, ask the Resident to delay departure, or send Elena Ruiz (Kendall-based) to secure the entry. Document the exception. Under no circumstances is the Home left unsecured.",
    rationale: "'Exterior entry that cannot be secured' is the literal P0 example in policy. The Home cannot be locked and the Resident leaves at 10:15. It was entered as P3, left UNASSIGNED, and auto-classified by the chat bot as 'routine carpentry'. This is the most severe misclassification in the queue.",
    updates: []
  },
  {
    id: "M-105",
    workstream: "In-Home Services",
    homeId: "H-1005",
    zone: "Coral Gables",
    priority: "P1 today (containment) / P2 Wed (repair)",
    risk: "AMBER",
    owner: "Jordan Lee",
    status: "New",
    action: "Warranty gate answered by 11:00 / containment on site 12:15",
    assignment: "CANCEL QuickFix 10:00-13:00. Marcus Bell delivers the compact mini-fridge 12:15-12:45. WARRANTY GATE at 08:30. Branch 1 (warranty at risk): manufacturer authorised service Wed 08:00-12:00, $0. Branch 2 (warranty unaffected): add Metro Appliance Mon 13:00-17:00, $129.",
    accessPlan: "Resident 12:00-15:00 Monday. No lockbox. The neighbour 'may open at 12:30' but is NOT yet authorised - not valid access under policy. Vendors use the loading entrance. Wednesday access must be confirmed today.",
    dependencies: "Manufacturer response by 11:00. Place a hold on Metro's single Monday slot at 08:45 and confirm or release it at 11:00. Ask the manufacturer in writing whether independent service voids or limits parts-and-labour coverage.",
    cost: "$0 (Branch 1) or $129 (Branch 2). Home limit $500.",
    communication: "Call at 08:30: cancel the morning visit and explain why, give the containment ETA, and state the commitment change from Monday to Wednesday explicitly. Food reimbursement question: acknowledge, do NOT promise, escalate to Alex, commit to an answer before 17:00, and ask the Resident to photograph discarded items and keep receipts.",
    fallback: "If the manufacturer cannot attend Wednesday, use Metro with the warranty intact. The mini-fridge sustains containment either way. If Metro repairs on Monday, verify a stable 2-4C with the Resident on Tuesday 09:00 BEFORE releasing the Wednesday slot - vendor completion is not verification.",
    rationale: "'Refrigerator failure with food at risk' is the literal P1 example. But the existing booking is unexecutable - QuickFix 10:00-13:00 against a Resident window of 12:00-15:00, with no lockbox and a vendor that will not narrow its window. The unit is also under manufacturer parts-and-labour warranty, which changes the correct repair path.",
    updates: []
  },
  {
    id: "M-106",
    workstream: "In-Home Services",
    homeId: "H-1006",
    zone: "Miami Beach",
    priority: "P1",
    risk: "AMBER",
    owner: "Maya Chen",
    status: "New",
    action: "Release 09:00 / COI SUBMITTED BY 14:00 (hard checkpoint, reminder set 13:30) / on site 16:00",
    assignment: "FlowRight Plumbing 16:00-18:00 (drain clearing plus camera if needed). RELEASE BY 09:00. FlowRight's COI is already accepted by this HOA.",
    accessPlan: "Resident home 16:00-19:00. HOA requires a current COI at least 2 hours before arrival, and vendors must check in at the service entrance.",
    dependencies: "Release by 09:00. COI submitted by 14:00 or entry is denied at the door. The coordinator must CONFIRM submission, not assume it - this is a silent blocker that lives in the Homes sheet, not the case.",
    cost: "$525 including camera if needed. Home limit $600. RISK: a main-line diagnosis may exceed the limit and require Homeowner approval.",
    communication: "Acknowledge within 30 minutes. Advise minimal water use and no repeat flushing until the visit. Confirm the 16:00 window. Notify immediately if the ETA changes.",
    fallback: "Rapid Rooter also covers Miami Beach but needs its own COI 2 hours ahead - the switch decision must therefore be made before 14:00, not at 16:00 when the vendor fails to appear.",
    rationale: "'Only toilet unusable' is the literal P1 example in policy - this is the only toilet in the Home. The toilet rising on flush combined with the shower drain gurgling indicates a main line or vent issue, not a simple clog, so the scope may be larger than a standard clear.",
    updates: []
  },
  {
    id: "M-107",
    workstream: "In-Home Services",
    homeId: "H-1007",
    zone: "Brickell",
    priority: "P2 - confirmed",
    risk: "AMBER",
    owner: "Jordan Lee",
    status: "New",
    action: "SUBMIT COI MONDAY (deadline Tue 09:00) / on site Wed 09:00",
    assignment: "Metro Appliance Repair, Wednesday 09:00-11:00 (licensed appliance repair, covers Brickell, 88% on-time).",
    accessPlan: "Resident available Wednesday 09:00-11:00 ONLY. Building requires a COI 24 hours in advance. No lockbox.",
    dependencies: "COI filed Monday, not Tuesday. Zero slack: the Resident's access window ends exactly at the case deadline (Wed 11:00). There is one attempt only.",
    cost: "$129. Home limit $500.",
    communication: "Confirm the Wednesday 09:00-11:00 visit and advise not to run the washer. Secure a backup access window from the Resident now, in case Wednesday is lost.",
    fallback: "QuickFix also covers Brickell but at 69% on-time and 63% first-visit resolution. If Wednesday is missed the next window is unknown, which is why an alternative window must be agreed in advance rather than negotiated after a failure.",
    rationale: "Correctly prioritised. The washer leaks only while running, the Resident has stopped using it and wiped up the water, so the fault is contained with no active damage. Nothing in the latest activity changes this.",
    updates: []
  },
  {
    id: "M-108",
    workstream: "In-Home Services",
    homeId: "H-1008",
    zone: "Pinecrest",
    priority: "P2 - MERGED with M-109",
    risk: "GREEN",
    owner: "Jordan Lee",
    status: "New",
    action: "Notify Resident Monday (2h notice required) / on site Tue 10:00",
    assignment: "TopShield Roofing Tuesday 10:00-12:00 - warranty inspection by the contractor who performed the prior patch.",
    accessPlan: "Resident flexible with 2 hours' notice. Working lockbox with permission - usable if the Resident cannot attend.",
    dependencies: "Monday notice to the Resident. NOTE: the inspection window ENDS EXACTLY at the case deadline (Tue 12:00) - zero slack if TopShield runs late.",
    cost: "$175, potentially $0 if the prior patch is warranty-responsible. Home limit $500.",
    communication: "Confirm to the Resident that both her app report and her phone call are now a single case with a single visit - she must not feel the call was ignored. Explain why it is not urgent (dry, flat, not spreading) and what will be checked.",
    fallback: "TopShield Wednesday 13:00-16:00, which breaches the deadline and must be renegotiated proactively rather than discovered. Marcus can take a moisture reading if there is any doubt the stain is genuinely dry.",
    rationale: "MERGED WITH M-109 (duplicate). The stain is dry, flat, not sagging and not growing, with no active drip - there is no active damage and no P1 justification. The roof was patched 4 months ago by TopShield, which raises possible warranty responsibility. Holding this at P1 was consuming attention needed by the genuine P0s.",
    updates: []
  },
  {
    id: "M-109",
    workstream: "In-Home Services",
    homeId: "H-1008",
    zone: "Pinecrest",
    priority: "CLOSED - duplicate of M-108",
    risk: "GREEN",
    owner: "Jordan Lee",
    status: "New",
    action: "Close 08:30",
    assignment: "CLOSE as duplicate. All work tracked under M-108.",
    accessPlan: "n/a - no separate visit",
    dependencies: "Confirm the merge with the Resident before closing, so the closure does not read as her call being dismissed.",
    cost: "$0",
    communication: "One message confirming both reports are unified under a single case, with the Tuesday inspection time.",
    fallback: "n/a",
    rationale: "Duplicate. Same Home, same ceiling stain, same hard deadline, same estimate, same approval limit as M-108. The Resident states verbatim that this is the same issue she submitted in the app the previous night. It entered a second time through a second channel (phone after app) because no de-duplication check exists at intake.",
    updates: []
  },
  {
    id: "M-110",
    workstream: "In-Home Services",
    homeId: "H-1010",
    zone: "Coral Gables",
    priority: "P2 - with declared trigger to P1",
    risk: "GREEN",
    owner: "Jordan Lee",
    status: "New",
    action: "Call Monday (acknowledge the delay) / on site Tue 08:00",
    assignment: "FlowRight Plumbing Tuesday 08:00-10:00, Coral Gables. Electric water heater, approximately 8 years old - most likely a failed lower element or thermostat.",
    accessPlan: "Resident available Tuesday 08:00-10:00. Resident access, no lockbox needed.",
    dependencies: "None blocking. If the diagnosis points to the electrical supply rather than the heater itself, this becomes licensed electrical work and transfers to BrightLine.",
    cost: "$225. Home limit $600.",
    communication: "The Monday call MUST acknowledge the delay explicitly - four days without contact is the Resident's actual experience and pretending otherwise damages credibility. Confirm Tuesday 08:00-10:00.",
    fallback: "If scope exceeds $600, Homeowner approval is required (responds same day). If the fault is electrical supply, transfer to BrightLine - do not let a plumber work outside licence.",
    rationale: "Intermittent lukewarm water is degraded rather than absent essential service, so P2 is defensible. Declared trigger: if it becomes fully cold before Tuesday, it escalates to P1. SLA FINDING: the case has been open 85 hours with no logged Belong response between 1 Oct and 4 Oct, against a P2 requirement of contact within 4 business hours.",
    updates: []
  },
  {
    id: "R-201",
    workstream: "Turnover / Home Readiness",
    homeId: "H-2001",
    zone: "Brickell",
    priority: "CRITICAL #1",
    risk: "RED",
    owner: "Priya Shah",
    status: "New",
    action: "PAINT ON SITE BY 10:30 / elevator extension requested 08:00 / QC complete Tue 10:00",
    assignment: "ReadySet Crew A 08:00-13:30 paint | Marcus Bell paint collection and delivery Monday, then smoke alarms and final QC Tuesday 08:20-10:00 | KeyGuard rekey 14:00-16:00 | Pristine cleaning 16:00-18:00 | Appliance retailer refrigerator delivery",
    accessPlan: "Building access Mon 08:00-18:00, Tue 08:00-15:00. Lockbox installed. FREIGHT ELEVATOR reserved 10:00-12:00 ONLY, against a retailer delivery ETA of 11:30-13:30 - direct conflict.",
    dependencies: "(1) Pre-approve the $64 paint BEFORE 08:15 so Marcus can purchase when the supplier opens. (2) Request elevator extension to 14:00 AND escalate to the retailer for a guaranteed pre-12:00 window - run both in parallel, do not rely on either. (3) The rekey depends on releasing M-104 at 08:15.",
    cost: "$64 paint + $1,499 approved base scope (Home limit $1,500) + $1,299 refrigerator already paid.",
    communication: "Confirm Tuesday 16:00 to the incoming Resident today. If the refrigerator is at risk, tell them TODAY, not Tuesday - they have booked movers and an elevator. Never promise a delivery window Belong does not control.",
    fallback: "Refrigerator: reschedule to Tuesday 08:00-11:00 within building access. If it fails entirely, provide a temporary unit plus a written agreement with the incoming Resident - a missing refrigerator is a required-appliance blocker under move-in policy and cannot be waived silently. Escalate to executive if the move-in must proceed incomplete.",
    rationale: "Signed lease, incoming Resident reconfirmed Tuesday 16:00, movers and building elevator booked and explicitly immovable. Under the 4-hour policy, final QC is due Tuesday 12:00, and building access on Tuesday ends at 15:00 - so effectively everything must complete Monday. This is the highest-value commitment on the board.",
    updates: []
  },
  {
    id: "R-202",
    workstream: "Turnover / Home Readiness",
    homeId: "H-2002",
    zone: "Coconut Grove",
    priority: "CRITICAL #2",
    risk: "RED",
    owner: "Priya Shah",
    status: "New",
    action: "APPROVAL 08:30 / ClearOut released 08:45 / ReadySet released 09:30",
    assignment: "ClearOut Hauling 09:30-11:30 (release 08:45) | ReadySet Crew B 12:00-17:00 (release 09:30) | Pristine cleaning Tue 16:00-18:00 | Final QC Marcus Bell Wed 08:00",
    accessPlan: "Vacant with a working lockbox. No HOA or building restrictions.",
    dependencies: "TWO SEPARATE AUTHORITIES: D1 ClearOut $680 under Priya's normal authority (below the $750 Home limit, no exception needed). D2 ReadySet $1,780 under the Manager signed-move-in exception. All four exception criteria are met: signed lease, outreach via two channels, credible itemised scope, clear threat to a committed move-in. Total exposure $2,460 against a $2,500 ceiling. Dependency chain is rigid: haul-out then paint then clean then QC.",
    cost: "$2,460 ($680 haul-out + $1,780 paint). Pristine cleaning cost is NOT quoted anywhere - verify at 08:00. If it exceeds roughly $40, the total crosses $2,500 and requires executive approval.",
    communication: "Written notice at 08:45 via THREE channels (email, SMS and WhatsApp - email and phone have each already failed twice), timed to land in the 14:00-20:00 window. It states the decision taken, the four criteria met, both itemised quotes, the cheaper alternative rejected and why (SunCoast finishes Wednesday afternoon and misses the move-in), and an objection deadline of 18:00 today. It informs; it does not ask permission.",
    fallback: "If additional scope appears on site, STOP and escalate to executive before authorising - do not absorb it under the existing exception with only $40 of headroom. Pre-agree the executive contact BEFORE releasing, not at 10:00 with a crew waiting. If Pristine cannot enter Tuesday, escalate MONDAY: Wednesday cleaning breaks the 4-hour QC rule.",
    rationale: "Signed lease, move-in Wednesday 12:00, QC due Wednesday 08:00. The Homeowner is in Europe, replies only 14:00-20:00 ET, and has not answered 4 outreach attempts over 2 days. Required scope is $2,460 against a $750 Home limit, and both vendor holds expire (08:45 and 09:30) BEFORE the Homeowner window opens. Waiting guarantees the move-in fails.",
    updates: []
  },
  {
    id: "R-203",
    workstream: "Turnover / Home Readiness",
    homeId: "H-2003",
    zone: "Pinecrest",
    priority: "HIGH - life-safety blocker",
    risk: "AMBER",
    owner: "Sofia Reyes",
    status: "New",
    action: "Release 09:00 / SafeGate on site 15:00 / compliance verified same day",
    assignment: "CANCEL Elena's 08:30 repair attempt. SafeGate Pool & Fence 15:00-17:00 (release 09:00) - qualified pool-barrier contractor who can verify self-closing and latching compliance | ReadySet Crew A Tue 08:00-12:00 touch-up | Pristine Tue 13:00-15:00 | Final QC Wed - OWNER TO BE ASSIGNED",
    accessPlan: "Vacant with a working lockbox. No access constraint.",
    dependencies: "Release by 09:00. UNQUOTED SCOPE: the case states 'landscape and touch-up remain' but neither has a quote, a vendor or a schedule slot. Touch-up must finish before Tue 13:00 because Pristine will not clean while paint is active. NO LANDSCAPING VENDOR EXISTS IN THE NETWORK - escalate Monday.",
    cost: "$425 gate (Home limit $500). Touch-up not quoted. Landscaping has no vendor and no price.",
    communication: "Confirm Thursday 09:00 to the incoming Resident. If landscaping cannot be resolved, tell them TODAY what will and will not be delivered at handoff - do not let them discover it on move-in day.",
    fallback: "SafeGate Tuesday 08:00-10:00 if Monday fails. If the gate needs parts, that decision must be taken Tuesday, not Wednesday. For landscaping: procure out of network or obtain an explicit decision that it is not a handoff blocker.",
    rationale: "The pool gate does not self-close or latch and the incoming family has two children. Elena's own inspection noted weak hinge tension in addition to the latch, and a Field Specialist cannot provide qualified compliance verification - the inventory note says the universal latch kit does not replace it. Move-in Thursday 09:00; QC due Wednesday 17:00.",
    updates: []
  },
  {
    id: "R-204",
    workstream: "Turnover / Home Readiness",
    homeId: "H-2004",
    zone: "Doral",
    priority: "MEDIUM",
    risk: "GREEN",
    owner: "Sofia Reyes",
    status: "New",
    action: "Vendor parking registration filed Monday / on site Tue 08:00",
    assignment: "Apex Climate Services Tuesday 08:00-11:00 - diagnostic plus filter replacement. Does not need Monday's emergency slot.",
    accessPlan: "Vacant with a working smart lock. VENDOR PARKING REGISTRATION REQUIRED - a silent blocker; file it Monday, not Tuesday morning.",
    dependencies: "Parking registration. RESOLVE THE PHOTOGRAPHY CONFLICT: the Tuesday 13:00 Doral slot is claimed by BOTH R-204 and O-301, and FrameReady lists only one Doral slot. R-204 has a signed lease and a Friday move-in, so listing photography appears unnecessary - confirm the purpose and cancel if it is listing work.",
    cost: "$139. Home limit $750.",
    communication: "No Resident (vacant). Confirm the Friday 15:00 date with the incoming Resident.",
    fallback: "Apex Wednesday 08:00-12:00. If the diagnosis shows nothing beyond the filter, a Field Specialist can replace it directly.",
    rationale: "The Home is vacant with no Resident impact, the system is running, and there is no active leak. The deadline (Thu 17:00) sits outside the 72-hour horizon and the move-in is Friday. 'High' overstated a dirty filter in an empty house and put it in competition with genuine emergencies.",
    updates: []
  },
  {
    id: "R-205",
    workstream: "Turnover / Home Readiness",
    homeId: "H-2005",
    zone: "Fort Lauderdale",
    priority: "LOW - no field capacity in 72h",
    risk: "AMBER",
    owner: "Sofia Reyes",
    status: "New",
    action: "Checklist issued Monday / scope to Homeowner Wednesday",
    assignment: "CANCEL Elena's 15:00-16:00 Fort Lauderdale trip. SunCoast performs the site walk alone against a Belong-supplied structured checklist.",
    accessPlan: "Vacant with a working lockbox - SunCoast can enter without a Belong resource present.",
    dependencies: "Belong-issued checklist (room by room, condition by surface, appliances with make and model, mandatory photo or video per item) to offset SunCoast's documented weak reporting. SECOND QUOTE REQUIRED: SunCoast is the ONLY vendor covering Fort Lauderdale, so a single-source vendor would otherwise be writing its own $3,200 scope.",
    cost: "$0 this week. The $3,200 scope is unapproved and exceeds the $1,000 Home limit - Homeowner approval required.",
    communication: "Written status to the Homeowner Monday; scope and cost Wednesday. The Homeowner replies in 1-2 days, so Wednesday issuance yields an answer by Thursday or Friday.",
    fallback: "If SunCoast's documentation proves inadequate, schedule a Belong assessment later in the week - planned and batched, not improvised on a Monday.",
    rationale: "No signed lease, no launch date, no approved scope. Kendall to Fort Lauderdale is 85 minutes each way: 230 minutes of Field Specialist time, 64% of Elena's productive day, for a Home with no commitment attached. Deprioritised for FIELD capacity - not abandoned: 18 days vacant is a genuine revenue problem, and it advances four steps this week through coordination alone.",
    updates: []
  },
  {
    id: "O-301",
    workstream: "Onboarding",
    homeId: "H-3001",
    zone: "Doral",
    priority: "MEDIUM",
    risk: "AMBER",
    owner: "Sofia Reyes",
    status: "New",
    action: "Confirm activation Tue afternoon / inspection Wed",
    assignment: "CANCEL Elena's Monday 13:00-14:00 onboarding inspection. Reschedule the inspection AND the photography to Wednesday, after activation is confirmed.",
    accessPlan: "Vacant with a working smart lock. Vendor registration required.",
    dependencies: "Utility activation Tuesday 12:00-16:00 must be CONFIRMED before anything is scheduled - do not book against a window that may slip. Cancelling also frees the contested Tuesday 13:00 Doral photography slot.",
    cost: "$0. Home limit $1,000. No repair approval needed yet.",
    communication: "Correct the Homeowner politely: the utility provider has confirmed Tuesday activation, not Monday. Set expectations for a Wednesday inspection.",
    fallback: "If activation slips past Tuesday, the Wednesday 17:00 deadline breaks - renegotiate on Tuesday when the slip is known, not on Wednesday when it is already missed.",
    rationale: "UTILITIES ARE OFF until Tuesday 12:00-16:00, confirmed by the utility provider at 07:40 Monday. The Homeowner's Sunday claim that they would be on by Monday is superseded by the later, authoritative fact. An inspection without power or water cannot assess HVAC, plumbing, the water heater, outlets or lighting - it guarantees an incomplete report and a return visit.",
    updates: []
  },
  {
    id: "O-302",
    workstream: "Onboarding",
    homeId: "H-3002",
    zone: "Miami Beach",
    priority: "MEDIUM case / CRITICAL action today",
    risk: "RED",
    owner: "Priya Shah",
    status: "New",
    action: "08:30 building requirements / 11:00 send / 17:00 CUTOFF",
    assignment: "CANCEL Marcus's 14:00-15:00 lockbox visit - the concierge will deny entry, wasting 2.2 hours of Field Specialist capacity. Secure Homeowner authorisation 11:00-13:00. Hold FrameReady Tuesday 09:00 against a 17:00 cutoff.",
    accessPlan: "Concierge-controlled access only. No keys and no lockbox with Belong. The Homeowner must add each company and person to the approved list. NO AUTHORISATION CURRENTLY EXISTS.",
    dependencies: "By 11:00 Luis must have obtained from BUILDING MANAGEMENT (not the concierge): the exact recipient address, the required format, the data needed per person, and the processing time. Confirmation must arrive IN WRITING FROM THE BUILDING - the Homeowner saying 'I sent it' is not access, because the concierge works from the list, not from the Homeowner's word.",
    cost: "$0. Exposure of $95 in failed-access fees if the photographer is dispatched unconfirmed.",
    communication: "WhatsApp at 11:00 sharp with a PRE-DRAFTED, ready-to-send email - the Homeowner said 'send exactly what the building needs', so asking him an open question wastes the window. Authorise Belong permanently, Marcus Bell by name, FrameReady and the photographer by name, a locksmith, and explicit permission to install a lockbox. Ask the Homeowner to copy Belong on the email to management.",
    fallback: "If there is no response today the Tuesday 09:00 deadline fails: cancel FrameReady, rebook Wednesday, and tell Priya TODAY rather than Tuesday morning. Retry WhatsApp in the same window on Tuesday.",
    rationale: "A vacant pre-listing condo with no Resident, no lease and no revenue commitment - the CASE is medium. But the Homeowner is overseas and reachable only 11:00-13:00 Miami time today, and that window does not reopen. Case priority and action urgency are different things; confusing them is what put a Field Specialist on the road to a building that will refuse him entry.",
    updates: []
  },
  {
    id: "O-303",
    workstream: "Onboarding",
    homeId: "H-3003",
    zone: "Kendall",
    priority: "MEDIUM",
    risk: "GREEN",
    owner: "Sofia Reyes",
    status: "New",
    action: "Confirm Monday / on site Tue 14:00",
    assignment: "BrightLine Electric Tuesday 14:00-16:00 - licensed electrical contractor, correct trade for panel and GFCI work.",
    accessPlan: "Vacant with a working lockbox. Panel access required.",
    dependencies: "$480 against a $500 Home limit - only $20 of margin. Instruct BrightLine to stop and notify BEFORE exceeding, rather than presenting an over-limit invoice. Have the Homeowner contact ready on Tuesday midday.",
    cost: "$480. Home limit $500.",
    communication: "No Resident. Keep the Homeowner contactable Tuesday midday in case the limit is exceeded (responds same day).",
    fallback: "BrightLine Wednesday 08:00-12:00. If scope exceeds the Home limit, Homeowner approval is required and costs one day - which is why the warning must come before the work, not after.",
    rationale: "The Home is vacant, the affected circuit is already off, there is no Resident and no listing date. This is a code-compliance item (open panel knockout, missing GFCI within six feet of the kitchen sink), not an active hazard. P1 put it in competition for Monday attention against genuine electrical and security emergencies.",
    updates: []
  },
  {
    id: "O-304",
    workstream: "Onboarding",
    homeId: "H-3004",
    zone: "Pinecrest",
    priority: "CRITICAL TODAY - irreplaceable",
    risk: "RED",
    owner: "Sofia Reyes",
    status: "New",
    action: "10:30 - ABSOLUTELY PROTECTED",
    assignment: "Marcus Bell 10:30-11:00 key handover (FIXED) plus lockbox installation 11:00-11:20.",
    accessPlan: "Homeowner handover only. No Belong keys until the handover occurs.",
    dependencies: "Marcus's Monday chain was rebuilt to give 40 minutes of buffer before 10:30. The R-201 smoke alarms were deliberately moved to Tuesday so this margin is not eroded to 10 minutes. Never place a 10-minute buffer in front of an irreplaceable commitment.",
    cost: "$0. Lockbox drawn from Coral Gables inventory.",
    communication: "Confirm with the Homeowner at 08:30 that Marcus arrives at 10:30. Record the lockbox code, serial number, a photograph and the written authorisation at installation.",
    fallback: "If Marcus is delayed, ANY Belong resource goes - Elena Ruiz or Luis Ortega. This is the one task with no substitute and no second chance: someone must be at that door at 10:30.",
    rationale: "The Homeowner can hand over keys ONLY Monday 10:30-11:00 and leaves for the airport immediately afterwards. There is NO alternate key source. Without the keys there is no lockbox, no Tuesday photography, and no access to the Home at all until the Homeowner returns from a trip of unknown length. This is the only genuinely irreplaceable commitment on the board.",
    updates: []
  }
];
