import type { QueueCase } from "./types";

/**
 * The open queue as inherited on Monday 08:00. Used to decide whether an
 * incoming message is a NEW issue or an update to work already open.
 *
 * Only the issue wording anchors a match. Sharing a Home or a trade is context,
 * not identity — a Home we already manage can have a brand-new problem.
 */
export const OPEN_QUEUE: QueueCase[] = [
  { id: "M-101", homeId: "H-1001", trade: "plumbing", status: "New - vendor not assigned",
    issue: "Repeat kitchen sink leak; water entered base cabinet",
    keywords: [/kitchen sink/, /under the sink/, /cabinet/, /supply/, /tighten/] },
  { id: "M-102", homeId: "H-1002", trade: "hvac", status: "Vendor tentative",
    issue: "Air conditioning not cooling",
    keywords: [/thermostat/, /compressor/, /outside unit/, /children/] },
  { id: "M-103", homeId: "H-1003", trade: "electrical", status: "Scheduled",
    issue: "Outlet sparked and produced burning odour; breaker now off",
    keywords: [/guest.?(room|bedroom)/, /lamp/, /breaker/, /lockbox/] },
  { id: "M-104", homeId: "H-1004", trade: "locksmith", status: "Unassigned",
    issue: "Front entry will not latch or deadbolt; Home cannot be secured",
    keywords: [/front (door|entry)/, /deadbolt/, /latch/, /secure/] },
  { id: "M-105", homeId: "H-1005", trade: "appliance", status: "Scheduled - access risk",
    issue: "Refrigerator is warming; food may spoil",
    keywords: [/fridge|refrigerator/, /food/, /neighbou?r/, /degrees/] },
  { id: "M-106", homeId: "H-1006", trade: "plumbing", status: "Awaiting dispatch",
    issue: "Only toilet backs up and shower drain gurgles",
    keywords: [/toilet/, /shower/, /gurgl/, /back(s|ing)? up/] },
  { id: "M-107", homeId: "H-1007", trade: "appliance", status: "New",
    issue: "Washer leaks only during use",
    keywords: [/\bwasher\b/, /underneath/, /when it runs/] },
  { id: "M-108", homeId: "H-1008", trade: "roofing", status: "New",
    issue: "Brown ceiling stain after rain; no active dripping",
    keywords: [/brown (spot|mark|stain)/, /ceiling/, /after (the )?rain/, /upstairs/] },
  { id: "M-109", homeId: "H-1008", trade: "roofing", status: "New - duplicate of M-108",
    issue: "Possible roof leak in upstairs bedroom (same report as M-108)",
    keywords: [/brown (spot|mark|stain)/, /ceiling/, /upstairs/, /roof/] },
  { id: "M-110", homeId: "H-1010", trade: "plumbing", status: "New",
    issue: "Hot water intermittent; currently lukewarm",
    keywords: [/hot water/, /lukewarm/, /water heater/] },
  { id: "R-201", homeId: "H-2001", trade: "turnover", status: "In progress",
    issue: "Paint, refrigerator delivery, smoke alarms, rekey, clean and QC before Tuesday move-in",
    keywords: [/paint/, /gallon/, /elevator/, /delivery/, /smoke alarm/, /rekey/, /% ?done/] },
  { id: "R-202", homeId: "H-2002", trade: "turnover", status: "Blocked - approval",
    issue: "Remove abandoned furniture, paint, clean and QC before Wednesday move-in",
    keywords: [/furniture/, /debris/, /haul/, /repaint/] },
  { id: "R-203", homeId: "H-2003", trade: "pool", status: "In progress",
    issue: "Pool gate does not self-close or latch; landscape and touch-up remain",
    keywords: [/pool/, /\bgate\b/, /self-?clos/, /latch/, /landscap/] },
  { id: "R-204", homeId: "H-2004", trade: "hvac", status: "New",
    issue: "HVAC cools only to 78; filter dirty",
    keywords: [/filter/, /\b78\b/, /cools only/] },
  { id: "R-205", homeId: "H-2005", trade: "turnover", status: "Site walk scheduled",
    issue: "Full turnover scope required; no committed move-in",
    keywords: [/site walk/, /full turnover/, /scope/] },
  { id: "O-301", homeId: "H-3001", trade: "general", status: "Inspection scheduled",
    issue: "Onboarding inspection and photography; utilities off until Tuesday",
    keywords: [/utilit/, /activation/, /inspection/, /photograph/] },
  { id: "O-302", homeId: "H-3002", trade: "photo", status: "Field visit scheduled",
    issue: "Install lockbox and complete photography; no access authorisation",
    keywords: [/concierge/, /authoriz/, /approved (access )?list/, /1804/, /lockbox/, /photographer/] },
  { id: "O-303", homeId: "H-3003", trade: "electrical", status: "Needs trade assignment",
    issue: "Open electrical-panel knockout and missing GFCI near kitchen sink",
    keywords: [/knockout/, /\bgfci\b/, /\bpanel\b/] },
  { id: "O-304", homeId: "H-3004", trade: "general", status: "Fixed handoff scheduled",
    issue: "Receive keys, install lockbox, preserve Tuesday photography",
    keywords: [/hand ?(over|off)/, /\bkeys\b/, /owner.{0,20}(town|airport|leav)/] },
];
